### ISSUE TITLE
VIEW EVENTS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Restaurant-Bookings-Project#1]
EPIC: <epic>

As a **User** I can **access the site** so that **I'm able to see upcoming events**.

**Acceptance Criteria**

- The Homepage will be a list of upcoming events.

- A user doesn't have to log in to see events or make a booking.

- The bookings page is accessible from a link on the navbar.

- The user can click on an event to expand it and see if they'd like to attend.

- A user can swap between a list or a grid view of the events.

- Any new event will be displayed on the site's homepage.

**Tasks**

- [x] Set up events page.

- [x] Make the events page the homepage.

- [x] Plan and create model for Events.

- [x] Set up a database to store events.

- [x] Test that Users can see events created by a Superuser.
