### ISSUE TITLE
VIEWING THE ABOUT SECTION'S CONTENT

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Restaurant-Bookings-Project#10]
EPIC: About Section

As a **User** I can **view the about section** so that **I know more about the venue**.

**Acceptance Criteria**

- A user can see the About section when they go to make a booking.

- Any modification to the About section will be displayed to the user.

**Tasks**

- [x] Set up About section.
- [x] Plan and create model for About section.
- [x] Test that Users can see this when accessing the bookings page.
