### ISSUE TITLE
MAKE A BOOKING

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Restaurant-Bookings-Project#3]
EPIC: Bookings Page

As a **User** I can **visit the site** so that **I can make a booking**.

**Acceptance Criteria**

- Users can access the bookings page from the homepage.

- Users can fill and submit a form with their booking request.

- The form will be accessible only to Superusers.

**Tasks**

- [ ] Set up bookings page.
- [ ] Add calendar feature to bookings form so users can view and choose a date they'd like to book.
- [ ] Set up a database to store bookings.
- [ ] Plan Model for Bookings.
