### ISSUE TITLE
VIEW BOOKING REQUESTS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Restaurant-Bookings-Project#4]
EPIC: Bookings Page

As a **Superuser** I can **access booking requests** so that **I can view and respond to them**.

**Acceptance Criteria**
- A superuser can create an account with their email.

- A superuser can log into their account.

- A superuser can create, edit and delete events.

- A superuser can view booking requests from the admin panel.

**Tasks**

- [ ] Set up admin page so that only a superuser can access it.

- [ ] All booking requests are accessible from the admin panel.

- [ ] Link database with booking requests to admin panel.
