### ISSUE TITLE
VIEW BOOKING REQUESTS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Restaurant-Bookings-Project#6]
EPIC: Booking Confirmation

As a **Superuser** I can **confirm or cancel booking requests** so that **I can manage all booking requests received**.

**Acceptance Criteria**

- Only a superuser can access booking requests.

- A superuser can approve booking requests.

- A superuser can cancel booking requests.

**Tasks**

- [ ] Link the bookings form to the homepage.

- [ ] Plan and create model.
 
- [ ] Test that booking request is received and is actionable by a Superuser only.
