### ISSUE TITLE
SORT & FILTER BOOKING REQUESTS RECEIVED

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Restaurant-Bookings-Project#7]
EPIC: Admin Panel Customisation

As a **Superuser** I can **sort and filter booking requests** so that **these are easier to manage**.

**Acceptance Criteria**
- A superuser can filter booking requests on the admin panel.

- A superuser can sort booking requests on the admin panel.

**Tasks**
- [ ] Plan which fields a superuser would benefit from being able to sort.

- [ ] Implement ways a superuser might want to sort incoming booking requests.

- [ ] Plan which fields a superuser would benefit from being able to filter.

- [ ] Implement ways a superuser might want to filter incoming booking requests.
